name: mood_log_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  fl_chart: ^0.68.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/epilogue_italic.ttf
        - asset: assets/fonts/epilogue.ttf
          style: italic

